[package]
name = "Rust-PL-Stresstest"
version = "0.1.0"
authors = ["Jaeyong Choi <jayong93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.8"
rand = "0.7.2"
lazy_static = "1.4.0"
ggez = "0.5.1"
structopt = "0.3.2"
